name: Benchmark

on:
  push:
    branches:
      - master

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  check_benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Check benchmark
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --bench=server -- --sample-size=15
